// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { Position } from "./Position";

export type InteractiveElement = { id: string, element_type: string, properties: JsonValue, position: Position, };
