// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomDetails } from "./RoomDetails";

export type ListRoomsResponse = { rooms: Array<RoomDetails>, };
