// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CursorPresence } from "./CursorPresence";
import type { SharedPresentation } from "./SharedPresentation";

/**
 * Detailed information about a room
 */
export type RoomDetails = { room_id: string, subscriber_count: number, client_ids: Array<string>, storage: SharedPresentation, client_presences: { [key in string]?: CursorPresence }, };
