// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Slide } from "./Slide";

export type SharedPresentation = { slides: Array<Slide>, current_slide_index: number, version: bigint, };
