// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotation } from "./Annotation";
import type { InteractiveElement } from "./InteractiveElement";

export type SlideType = { "type": "Regular", "data": { content: string, annotations: Array<Annotation>, } } | { "type": "Video", "data": { url: string, autoplay: boolean, current_time: number, } } | { "type": "Interactive", "data": { content: string, interactive_elements: Array<InteractiveElement>, } } | { "type": "Poll", "data": { question: string, options: Array<string>, results: Array<number>, } };
