// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlideType } from "./SlideType";

export type Slide = { id: string, title: string, slide_type: SlideType, };
