// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserState = { name: string, avatar_url: string | null, is_typing: boolean, };
